baseURL = "/"
languageCode = "en-us"
title = "Hacktoberfest Sheffield 2020"
description = "Materials for 'Hacktoberfest Sheffield 2020'"
pygmentsUseClasses=true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html", '\.knit\.md$', '\.utf8\.md$']

[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Hacktoberfest Sheffield 2020"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/RSE-Sheffield/hacktoberfest2020"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='far fa-fw fa-copy'></i> Snippets"
url = "/snippets"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 40

[params]
  editURL = "https://github.com/RSE-Sheffield/hacktoberfest2020/edit/main/content/"
  description = "Hacktoberfest Sheffield 2020"
  author = "Sheffield RSE Team"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "rse-learn"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.reveal_hugo]
 theme = "white"
 load_default_plugins = false
 plugins = [
   "reveal-js/plugin/zoom-js/zoom.js",
   "reveal-js/plugin/notes/notes.js",
 ]
